- name: Install ansible and download my playbooks for system management
  hosts: all
  tasks:
      # Ansible from official repos is ancient - use PPA
      
    - name: install latest Ansible
      apt: name=ansible state=latest

      become: yes

    - name: clone ansible-system-setup repository
      git: 
        repo: "{{ github_url }}/weinix/ansible-workstation-setup"
        dest: "{{ ansible_setup_path }}"
        version: devel
      register: task_result
      failed_when:
        - task_result is failed
        - '"Local modifications exist in repository" not in task_result.msg'

    - name: configure git user email
      git_config:
        key: user.email
        value: wei.w.wang@gmail.com
        repo: "{{ ansible_setup_path }}"

    # - name: install python libraries
    #   pip:
    #     requirements: "{{ ansible_setup_path }}/requirements.txt"
    #     extra_args: --user
